name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - run: npm ci
      - uses: rharkor/caching-for-turbo@v1.5
      - run: npm test
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            packages/*/coverage/
